### ISSUE TITLE
ZipLibrary is causing "Protected by Adobe DRM" error on kobo

### ISSUE THREAD

**Issue by JeremyAube** [Michael-F-Bryan/mdbook-epub#31] opened 2020-06-17 16:50 UTC
https://github.com/Michael-F-Bryan/mdbook-epub/blob/640a81209b9de4af8da082222f31f62dc9d21af0/src/generator.rs#L28

The usage of ZipLibrary causes error "Protect by Adobe DRM" when trying to open the epub file on an e-reader (Tested on Kobo Clara HD).

To fix the issue I suggest the same solution as https://github.com/lise-henry/crowbook/issues/13 which is to use zip command and libzip as a fallback if the zip command is not available.

**Comment by JeremyAube** [comment] 2020-06-17 17:32
## Temporary fix

    run unzip <book-name>.epub to unzip the book;
    run rm <book-name>.epub
    run zip -rX <book-name>.epub mimetype META-INF OEBPS to rezip the book;

you can then transfer the new book to your kobo and it should work as expected.

**Comment by Michael-F-Bryan** [comment] 2020-06-18 02:22
I'm going to reopen this because making the user manually post-process a book isn't really a solution... That said, I won't be putting time into troubleshooting the issue because I don't render books to EPUB any more. I'm happy to review PRs though.

If `ZipLibrary` is what's triggering the *"Protected by Adobe DRM"* then you should create an issue against [the `epub-builder` repo](https://github.com/lise-henry/epub-builder) so they can address the issue.

**Comment by Michael-F-Bryan** [comment] 2020-06-18 07:25
Closing as a duplicate of #28

**Closed by Michael-F-Bryan** 2020-06-18 07:25 UTC
