### ISSUE TITLE
#rustdoc_include does not work

### ISSUE THREAD

**Issue by mabl** [Michael-F-Bryan/mdbook-epub#30] opened 2020-06-11 21:12 UTC
Building the "The Rust Programming Language" book from master results in many `{{#rustdoc_include path}}` listings not being included. I'm not clear on where this comes from, since it works in mdbook.

**Comment by Michael-F-Bryan** [comment] 2020-06-12 02:40
I don't think `rustdoc_include` has anything to do with `mdbook-epub`. Does The Book use its own custom preprocessor? If so, they may have set it to only run when being consumed by the HTML backend.

**Comment by mabl** [comment] 2020-06-12 05:17
The `rustdoc_include` is part of `mdbook`, see [here](https://rust-lang.github.io/mdBook/format/mdbook.html). So I would assume that these should just be parsed also in mdbook-epub. But I am just learning rust, hence the book, and have no deep overview about the architecture. Greping for  `rustdoc_include` does not lead to any special preprocessors.

**Comment by mabl** [comment] 2020-06-12 06:00
So I am using the --standalone option. If I understand it correctly, the preprocessors are not applied since `MDBook::execute_build_process` is not used by the `run()` method of `mdbook-epub` , which would transform the book with the preprocessors. (If they are specifically enabled in the `book.toml`.)

**Comment by blandger** [comment] 2020-11-27 20:35
That issue is fixed in two branches for two projects:
**mdbook-epub**
https://github.com/Michael-F-Bryan/mdbook-epub/compare/master...blandger:add_links_preprocessing
**mdbook**
https://github.com/rust-lang/mdBook/compare/master...blandger:master

I've reused pre-processor functionality inside mdbook-epub by using existing mdbook code. The mdbook is updated to expose those functionality for external world.
But I have a big doubts that my changes will be accepted in mdbook, as It looks as dead.

**Comment by blandger** [comment] 2021-04-29 20:33
Link pre-processor has added clonning capability so it can be cloned from mdbook context into mdbook-epub context and used for processing chapter by chapter. Original link pre-processor can process only the whole book, not chapter by chapter as in epub logic works.

**Comment by blandger** [comment] 2022-01-22 09:18
You can get better working version from my fork here
https://github.com/blandger/mdbook-epub/tree/add_links_preprocessing

It contains fixes in two libraries 
**epub-builder** fix for hardware devices. It still in review by owner 
https://github.com/lise-henry/epub-builder/pull/15

Modified mdbook source that can correctly pre-process '#rustdoc_include' links.
https://github.com/blandger/mdbook-epub/blob/3e9e66e1a836afa7648095653c7bf16212e20c6f/Cargo.toml#L42
I don't see ability to propose such changes into original mdbook master branch, sorry.

**Closed by blandger** 2022-01-22 09:18 UTC

**Comment by yuuyins** [comment] 2023-02-05 15:01
>  I don't see ability to propose such changes into original mdbook master branch, sorry.

what about this repo's master?

thanks for the work btw!

**Comment by blandger** [comment] 2023-02-05 15:38
> what about this repo's master?
Which one ?? What repo do you mean ?

A **epub-builder** crate contains proposed fixes. 

It's not realistic to propose changes into mdbook repo which are needed by mdbook-epub. Those mdbook changes are available in my branch **add_links_preprocessing**. So the following scenario is possible : fetch mdbook changed source from branch add_links_preprocessing, build them, then build mdbook-epub with modified mdbook lib.

**Comment by yuuyins** [comment] 2023-02-05 16:23
i meant merging [add_links_preprocessing](https://github.com/blandger/mdBook/tree/feature/links_preprocessor) into michael-f-bryan/mdbook-epub/master; or at lease rebase/merge on your own fork. i was confused if you meant `rust-lang/mdbook/master` or `michael-f-bryan/mdbook-epub`, but now i see it seems the latter is a proposition of changes to the former, so can't merge the links preprocessing into michael-f-bryan/mdbook-epub/master.

It is just that I want #rustdoc_include to work with mdbook-epub directly. I'll see if I can do what you suggest.

**Comment by blandger** [comment] 2023-02-05 18:32
Yes, michael-f-bryan/mdbook-epub can't work without changes landed to rust-lang/mdbook/master.
Since that is not realistic to propogate them into rust-lang/mdbook/master there is not sence to push them into michael-f-bryan/mdbook-epub too.

**Comment by dieterplex** [comment] 2023-02-07 09:28
Without fine-grained control to handle each chapter, preprocessing whole book is possible. 
Check out [my fork](https://github.com/dieterplex/mdbook-epub) and run the example to build the book
```
cargo run --example build_trpl -- --dest . book/
```

**Comment by dieterplex** [comment] 2023-02-12 12:42
I'm not sure what's the problem here and couldn't reproduce it. Download prebuild one here, https://dieterplex.github.io/rust-ebookshelf, if you just need the book, or submit an issue to my repo.
